adds Dockerfile and build workflow for CSV provider
eclipse/kuksa.val.feeders pull request #104
Opened 2023-05-30 12:29 UTC by eriksven

2023-05-30 14:53 UTC, lukasmittag requested changes
See comments

2023-05-30 16:08 UTC, eriksven commented
@lukasmittag thank you for your feedback. I updated the PR accordingly.

2023-05-31 11:41 UTC, lukasmittag requested changes
just one minor change :)

2023-05-31 11:41 UTC, lukasmittag commented on csv_provider/Dockerfile
> +# By default we use certificates and tokens from kuksa_certificates, so they must be included
delete comment as well

2023-06-01 07:00 UTC, eriksven commented on csv_provider/Dockerfile
> +# By default we use certificates and tokens from kuksa_certificates, so they must be included
Done

2023-06-01 07:27 UTC, lukasmittag approved these changes

2023-06-01 07:54 UTC, merged